### ISSUE TITLE
Шаблон бакалаврской требует disser.cls

### ISSUE THREAD

**Issue by 7aitsev** [ejiek/latex_templates#14]
Попробовал собрать `thesis.tex`, но словил ошибку: 

```
    csse-fcs.cls // line 96 // ! LaTeX Error: File `disser.cls' not found.Type X to quit or <RETURN> to proceed,or enter new name. (Default extension: cls)Enter file name:! Emergency stop.<read > \LoadClass{disser}[2011/11/29]
```

Я так понимаю, речь идет о классе из шаблона [disser](https://www.ctan.org/tex-archive/macros/latex/contrib/disser)?
У меня MikTex 2.9

**Comment by ejiektpobehuk** [comment]
Пока без понятия, в чём косяк.
Скоро разберёмся!

**Comment by dAN0n** [comment]
Косяк в использовании шаблоном пакета disser, который по дефолту отсутствует и в MiKTeX, и в TeXLive, поэтому требующий скачивания с CTAN и пляски с его установкой. То есть из-под коробки шаблон работать не будет. В качестве решения можно попробовать поместить этот пакет в папку с шаблоном и вызывать disser именно оттуда.

**Comment by ejiektpobehuk** [comment]
disser есть в TeXLive. Поднял виртуалочку Ubuntu 15.10 (GNU/Linux 4.2.0-27-generic x86_64), всё ок из коробки.
Версия TeXLive `2015.20150625-1ubuntu1`
собирал pdflatex'ом.

**Comment by ejiektpobehuk** [comment]
@7aitsev, поскольку MiKTeX виндовая тема, просто так проверить работоспособность мне не удасться (ибо не винды). @dAN0n предполагает, что пакет disser не подтягивается по причине отсутствия в источниках миктеха.
Как только появиться время, мы решим проблему. Но сейчас я был бы признателен, если бы ты попробовал поставить disser самостоятельно и отписался о результатах!
[Вот ](http://mirrors.ctan.org/macros/latex/contrib/disser/README.ru) русское readme на всякий случай =]

**Comment by 7aitsev** [comment]
@ejiek попробую до завтра.

**Comment by 7aitsev** [comment]
@ejiek,
- скачал архив [.tds](https://sourceforge.net/projects/disser/) с Sourceforge
- распаковал в `C:\Program Files\MiKTeX\2.9\` - это же и есть `texmf`?
- выполнил mktexlsr от администратора, программа пропускает вышеуказанный путь:
  ![index](https://cloud.githubusercontent.com/assets/10958284/14590328/36994936-0500-11e6-9c9b-1f2ce224b84a.jpg)
- поэтому запустил Settigns (Administrator), там обновил FNDB и Update Formats.
- скомпилировал `thesis.txt`, получил ошибки:
  ![default](https://cloud.githubusercontent.com/assets/10958284/14590341/91be2ff2-0500-11e6-846d-db51d75101d3.PNG)
  Полный лог приаттачил.
  [thesis.log.txt](https://github.com/ejiek/latex_templates/files/222868/thesis.log.txt)

Просто с `disser.cls` в `...latex_templates\bachelor_thesis` компилировал - ничего не вышло.

Еще я не проверял

> amsfonts, amsmath, amssymb, caption, cmap, graphicx, ifpdf, kvoptions, natbib, hyperref, subcaption, wrapfig, а также пакеты для поддержки русского языка.

потому что @dAN0n сказал, что не надо.

**Comment by ejiektpobehuk** [comment]
Проблема МиКТеХ'а полностью не решена, но вопрос данного тикета исчерпан.
Проверял на 2.9 в виртуалке десятки.
Поправлено в 5ed4127e4d9a15f885f0bde3de7fdd0565fbdc6b
