### ISSUE TITLE
TODO: объединить презенташки

### ISSUE THREAD

**Issue by ejiektpobehuk** [ejiek/latex_templates#5]
Взять всё полезное из beamer_pics (например, расположение картинок на слайде) и укомплектовать в presentation.

**Comment by dAN0n** [comment]
Там полезным является только окружение _picture_ на 5-ом слайде, для которого даже дополнительные пакеты не требуются. Просто добавить какой-нибудь минимальный пример с ним и забыть.
Краткая инфа об окружении есть, например, [здесь](https://ru.sharelatex.com/learn/Picture_environment).

**Comment by ejiektpobehuk** [comment]
Исходный шаблон удалён по причине перенесения всех особенностей в общий шаблон презентаций.
